" Vundle setup below
set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim' " required
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'miyakogi/conoline.vim'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/nerdtree'
Plugin 'rust-lang/rust.vim'
Plugin 'ycm-core/YouCompleteMe'
Plugin 'pangloss/vim-javascript'

call vundle#end()
filetype plugin indent on

syntax on
setlocal spell spelllang=en_us

set hlsearch
set incsearch
set ignorecase
set smartcase
set ruler
set colorcolumn=100
color desert
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey40
set visualbell
set backspace=indent,eol,start
set number relativenumber
set t_Co=256
set tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
set splitright
set splitbelow
set shell=/bin/bash
set encoding=utf-8
set updatetime=100 " helpfull for git gutter

" Code folding
set foldmethod=indent
set foldlevel=99
noremap <space> za

let g:gitgutter_enabled = 1

" Spell-check settings
hi clear SpellBad
hi SpellBad cterm=underline,bold ctermfg=red
" Set style for gVim
hi SpellBad gui=undercurl

" ESC delay
set timeoutlen=1000 ttimeoutlen=10

" Set CTRLP to search all project modules
let g:ctrlp_working_path_mode = ''

" Show hidden files with NERDTree
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.git$', '__pycache__', '.DS_Store', 'node_modules', 'cdk.out']

" https://thoughtbot.com/blog/faster-grepping-in-vim
" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor
  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
" bind \ (backward slash) to grep shortcut
command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
nnoremap \ :Ag<SPACE>

" Setup python venv for vim
if has('mac')
let g:python3_host_prog='/Users/justinmburrous/.venv/neovim/bin/python3'
elseif has('unix')
let g:python3_host_prog='/home/justinmburrous/.venv/neovim/bin/python3'
endif
